config/routes.rb
Rails.application.routes.draw do
	get '/.well-known/acme-challenge/Gcl13AN0SUH1veBZY_05y2Yv-WUWno3N5fG_2oV7h8A' => 'welcome#letsencrypt'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951/' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.html' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.txt' => 'welcome#loaderio'

  devise_for :users, scope: :admin, path: 'admin', skip: [:registrations, :omniauth_callbacks]

	get '/issue-desktop', to: redirect('/')
	get '/issue-mobile/:id', to: redirect('/m-issue/%{id}')
	get '/issue-desktop/:id', to: redirect('/issue/%{id}')
	get '/issue-archive', to: redirect('/')
	get '/archive-desktop/:id', to: redirect('/archives/%{id}')
	get '/archive-mobile/:id', to: redirect('/m-archives/%{id}')

  scope :admin, :module => 'admin' do
    resources :materials
		resources :author
		resources :comments

    resources :issues do
      resources :articles, except: [:index, :show, :new] do
        collection { patch :sort }
      end
    end

    scope :path => '/issues/:issue_id/:article_id' do
      resources :pages, except: [:show] do
        collection { patch :sort }

        delete 'thumbnail' => 'pages#remove_thumb', as: :remove_thumb

        resources :hyperlinks
      end

      resources :media, except: [:show] do
        collection { patch :sort }
      end

      post 'media/multiple' => 'media#multiple', as: :multiple_media
    end

    resources :analytics

    resources :users

    scope :account do
      get   'settings' => 'account#index',    as: :account_settings
      patch 'password' => 'account#password', as: :account_password
      patch 'profile'  => 'account#profile',  as: :account_profile
    end

    get '/' => 'issues#index'
  end

  namespace :api do
    namespace :v1 do
      resources :issues, only: [] do
        resources :pages, only: [:index, :show], param: :position
      end
    end
  end

  devise_for :users, only: [:omniauth_callbacks], path: '', controllers: { omniauth_callbacks: "auth/omniauth_callbacks" }

  resources :comments

  resources :materials, path: 'm', only: [] do
    get '(:id)' => 'materials#show', as: :show
  end

  resources :issues, path: '', only: [] do
    get 'advertisement' => 'issues#advertisement', as: :advertisement
    get 'interstitial'  => 'issues#interstitial',  as: :interstitial

    get '/preview/(:id)' => 'issues#previewed', as: :previewed
    get '(:id)' => 'issues#published', as: :published

    get '/:article_id/gallery' => 'issue_media#index', as: :gallery
  end
  root 'issues#published'

end

app/views/admin/pages/_buttons.html.erb
<% unless @issue.pages.empty? %>
	<%= link_to issue_previewed_url(@issue.preview_token, subdomain: 'www'), :class => 'btn btn-labeled btn-default', target: '_blank' do %>
		<span class="btn-label"><i class="fa fa-eye"></i></span> Preview
	<% end %>
<% end %>

<% if controller_name != 'pages' %>
	<%= link_to pages_path, :class => 'btn btn-labeled btn-default' do %>
		<span class="btn-label"><i class="fa fa-file-o"></i></span> Pages
	<% end %>
<% end %>

app/views/admin/pages/_caption.html.erb
<% if can?(:administrate, Page) %>
    <div class="caption">
		<p class="no-margin">
			<%= link_to('Edit', edit_page_path(@issue, @article, page), :class => 'label label-default') %>

			<%= link_to 'Links', page_hyperlinks_path(@issue, @article, page), :class => 'label label-default' %>

			<%= link_to('Remove', page_path(@issue, @article, page), method: :delete, :class => 'label label-danger', data: { confirm: 'Are you sure you want to remove this page?' }) %>

			<p>A: <%= page.position %> | M: <%= page.master_position %></p>
		</p>
	</div>
<% end %>

app/views/admin/pages/edit.html.erb
<% content_for :title do %>
	<%= render 'admin/shared/heads' %>
 	<p>PAGE EDITOR</p>
<% end %>

<% content_for :buttons do %>
	<%= link_to pages_path(@issue, @page.article, @page), :class => 'btn btn-labeled btn-default' do %>
		<span class="btn-label"><i class="fa fa-list"></i></span> Back to Page Gallery
	<% end %>
<% end %>

<% content_for :page_content do %>
<div class="col-md-8" id="edit-page">
	<div class="panel panel-default">
		<div class="panel-heading">Edit Page</div>

		<%= simple_form_for(@page, url: page_path(@issue, @article, @page), method: :patch) do |f| %>
			<div class="panel-body">
				<div class="form-group">
					<div class="well" style="padding: 10px">
						<%= @page.friendly_id %>
					</div>
				</div>
				<div class="form-group">
					<%= f.input :full_page_ad, label: 'This page should trigger an interstitial advertisement.', error: false %>

					<%= f.input :advertisement_thumb, label: 'Thumbnail for advertisement (optional)', error: false, input_html: { :class => 'form-control' } %>

					<%= f.input :position, as: :hidden, error: false %>

					<% if @page.advertisement_thumb? %>
						<div class="well" style="float: left; width: 100%; padding: 14px">
							<div class="col-md-8">
								<%= File.basename @page.advertisement_thumb_url %>
							</div>
							<div class="col-md-4">
								<div class="text-right">
									<%= link_to('[remove]', page_remove_thumb_path(@issue, @article, @page), method: :delete, data: { confirm: 'Are you sure?' }) %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
			<div class="panel-footer">
				<%= f.button :submit, :class => 'btn btn-primary btn-sm' %>
			</div>
		<% end %>
	</div>
</div>

<div class="col-md-4" id="edit-hyperlinks">
	<% unless @page.advertisement_thumb.blank? %>
		<div class="panel panel-default">
			<div class="panel-heading">Thumbnail</div>
			<div class="panel-body" id="article-thumbnail">
				<%= image_tag(@page.thumbnail_url) %>
			</div>
		</div>
	<% end %>
</div>
<% end %>

<%= render 'admin/shared/layout' %>

app/views/admin/pages/index.html.erb
<% content_for :title do %>
	<%= render 'admin/shared/heads' %>
	<p>PAGE GALLERY</p>
<% end %>

<% content_for :buttons do %>
	<%= render 'admin/pages/buttons' %>
<% end %>

<% content_for :page_content do %>
<div id="pages" class="<%= @issue.role.downcase %> sortable" data-href="<%= sort_pages_url(@issue, @article) %>">
	<% unless @pages.nil? %>
		<% @pages.each do |page| %>
			<div class="col-md-3" data-identifier="<%= page.id %>">
				<div class="thumbnail">
					<%= render 'admin/pages/caption', page: page %>
					<%= image_tag page.image_url(:small) %>
				</div>
			</div>
		<% end %>
	<% end %>

	<div class="col-md-3">
		<% if can?(:administrate, Page) %>
			<a class="thumbnail text-centered" id="create-page">
				<i class="fa fa-plus fa-5x" id="btn-add"></i> <p>Add New Page(s)</p>
			</a>

			<%= form_for(:page, url: pages_path(@issue, @article), html: { multipart: true, id: 'new_page' }, method: :post) do |f| %>
			     <%= f.file_field :image, multiple: true, name: "pages[image][]", :class => 'hidden', onchange: 'this.form.submit()' %>
			<% end %>
		<% end %>
	</div>
</div>
<% end %>

<%= render 'admin/shared/layout' %>