config/routes.rb
Rails.application.routes.draw do
	get '/.well-known/acme-challenge/Gcl13AN0SUH1veBZY_05y2Yv-WUWno3N5fG_2oV7h8A' => 'welcome#letsencrypt'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951/' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.html' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.txt' => 'welcome#loaderio'

  devise_for :users, scope: :admin, path: 'admin', skip: [:registrations, :omniauth_callbacks]

	get '/issue-desktop', to: redirect('/')
	get '/issue-mobile/:id', to: redirect('/m-issue/%{id}')
	get '/issue-desktop/:id', to: redirect('/issue/%{id}')
	get '/issue-archive', to: redirect('/')
	get '/archive-desktop/:id', to: redirect('/archives/%{id}')
	get '/archive-mobile/:id', to: redirect('/m-archives/%{id}')

  scope :admin, :module => 'admin' do
    resources :materials
		resources :author
		resources :comments

    resources :issues do
      resources :articles, except: [:index, :show, :new] do
        collection { patch :sort }
      end
    end

    scope :path => '/issues/:issue_id/:article_id' do
      resources :pages, except: [:show] do
        collection { patch :sort }

        delete 'thumbnail' => 'pages#remove_thumb', as: :remove_thumb

        resources :hyperlinks
      end

      resources :media, except: [:show] do
        collection { patch :sort }
      end

      post 'media/multiple' => 'media#multiple', as: :multiple_media
    end

    resources :analytics

    resources :users

    scope :account do
      get   'settings' => 'account#index',    as: :account_settings
      patch 'password' => 'account#password', as: :account_password
      patch 'profile'  => 'account#profile',  as: :account_profile
    end

    get '/' => 'issues#index'
  end

  namespace :api do
    namespace :v1 do
      resources :issues, only: [] do
        resources :pages, only: [:index, :show], param: :position
      end
    end
  end

  devise_for :users, only: [:omniauth_callbacks], path: '', controllers: { omniauth_callbacks: "auth/omniauth_callbacks" }

  resources :comments

  resources :materials, path: 'm', only: [] do
    get '(:id)' => 'materials#show', as: :show
  end

  resources :issues, path: '', only: [] do
    get 'advertisement' => 'issues#advertisement', as: :advertisement
    get 'interstitial'  => 'issues#interstitial',  as: :interstitial

    get '/preview/(:id)' => 'issues#previewed', as: :previewed
    get '(:id)' => 'issues#published', as: :published

    get '/:article_id/gallery' => 'issue_media#index', as: :gallery
  end
  root 'issues#published'

end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < Admin::BaseController
  load_and_authorize_resource :class => Issue

  before_action :set_material, only: [:edit, :update, :destroy]

  # GET /admin/materials
  def index
  	@materials = Issue.materials.order(:created_at)
  end

 # GET /admin/materials/new
  def new
  	@material = Issue.new
  end

  # POST /admin/materials
  def create
    @material = Issue.new material_params.merge(creator: current_user)

    if @material.save
      redirect_to materials_path, notice: 'Material was successfully created'
    else
      flash.now[:danger] = @material.first_error_message
      render :new
    end
  end

  # GET /materials/:id/edit
  def edit
  end

  # PATCH /materials/:id
  def update
    if @material.update(material_params)
      redirect_to edit_material_path(@material), notice: 'Material was successfully updated'
    else
      flash.now[:danger] = @material.first_error_message
      render :edit
    end
  end

  # DELETE /materials/:id
  def destroy
  end

  protected
    def material_params
      params.require(:issue).permit(:number, :alias_name, :title, :published_on).merge(role: 'Material')
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material_issue, only: [:show]
  before_action :set_page

  layout 'client'

  def show
  end

  protected
    def set_material_issue
      @issue = Issue.materials.find_by(friendly_id: params[:material_id].to_s)
    end

    def set_page
      @page = @issue.pages.where(friendly_id: params[:id]).take
    end
end

app/views/admin/materials/edit.html.erb
<% content_for :title do %>
	<h4>Supplemental</h4>
<% end %>

<% content_for :buttons do %>

<% end %>

<% content_for :page_content do %>

<% end %>

<%= render 'admin/shared/layout' %>

app/views/admin/materials/index.html.erb
<% content_for :title do %>
  <h4>Supplemental</h4>
<% end %>

<% content_for :buttons do %>
    <%= link_to new_material_path, :class => 'btn btn-labeled btn-default' do %>
    	<span class="btn-label"><i class="fa fa-plus"></i></span> Create Supplemental
    <% end %>
<% end %>

<% content_for :page_content do %>
	<div id="issues" class="row">
		<% @materials.sort_by{|issue| issue.title}.each do |material| %>
			<div class="col-md-3 thumbnail">
				<%= link_to pages_path(material, material.first_article), :class => 'issue' do %>
					<%= thumbnail_for(material) %>
				<% end %>
				<%= render 'admin/issues/caption', issue: material %>
				<%= link_to pages_path(material, material.first_article) do %>
					<p class="title text-centered"><%= material.title %></p>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

<%= render 'admin/shared/layout' %>

app/views/admin/materials/new.html.erb
<% content_for :title do %>
  <h4>Supplemental</h4>
<% end %>

<% content_for :buttons do %>
    <%= link_to materials_path, :class => 'btn btn-labeled btn-default' do %>
    	<span class="btn-label"><i class="fa fa-list"></i></span> Back to Documents
    <% end %>
<% end %>

<% content_for :page_content do %>
<div class="col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading">Create Supplemental Document</div>
		<%= simple_form_for(@material, url: materials_path, method: :post) do |f| %>
			<div class="panel-body">
				<div class="form-group">
					<%= f.input :title, error: false, input_html: { :class => 'form-control' } %>
				</div>
				<div class="form-group hidden">
					<%= f.input :number, collection: issue_numbers, selected: issue_count, error: false, input_html: { :class => 'form-control' } %>
				</div>
        <div class="form-group">
					<%= f.input :alias_name, label: 'Custom URL (m-<name> / <name>, i.e. m-issue / issue)', error: false, input_html: { :class => 'form-control' } %>
        </div>
				<div class="form-group">
					<%= f.input :orientation, collection: ['mobile', 'desktop'], error: false, input_html: { :class => 'form-control' } %>
				</div>
	    </div>
			<div class="panel-footer">
				<%= f.button :submit, 'Create Supplemental', :class => 'btn btn-primary btn-sm' %>
			</div>
		<% end %>
	</div>
</div>

<% end %>

<%= render 'admin/shared/layout' %>