config/routes.rb
Rails.application.routes.draw do
	get '/.well-known/acme-challenge/Gcl13AN0SUH1veBZY_05y2Yv-WUWno3N5fG_2oV7h8A' => 'welcome#letsencrypt'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951/' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.html' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.txt' => 'welcome#loaderio'

  devise_for :users, scope: :admin, path: 'admin', skip: [:registrations, :omniauth_callbacks]

	get '/issue-desktop', to: redirect('/')
	get '/issue-mobile/:id', to: redirect('/m-issue/%{id}')
	get '/issue-desktop/:id', to: redirect('/issue/%{id}')
	get '/issue-archive', to: redirect('/')
	get '/archive-desktop/:id', to: redirect('/archives/%{id}')
	get '/archive-mobile/:id', to: redirect('/m-archives/%{id}')

  scope :admin, :module => 'admin' do
    resources :materials
		resources :author
		resources :comments

    resources :issues do
      resources :articles, except: [:index, :show, :new] do
        collection { patch :sort }
      end
    end

    scope :path => '/issues/:issue_id/:article_id' do
      resources :pages, except: [:show] do
        collection { patch :sort }

        delete 'thumbnail' => 'pages#remove_thumb', as: :remove_thumb

        resources :hyperlinks
      end

      resources :media, except: [:show] do
        collection { patch :sort }
      end

      post 'media/multiple' => 'media#multiple', as: :multiple_media
    end

    resources :analytics

    resources :users

    scope :account do
      get   'settings' => 'account#index',    as: :account_settings
      patch 'password' => 'account#password', as: :account_password
      patch 'profile'  => 'account#profile',  as: :account_profile
    end

    get '/' => 'issues#index'
  end

  namespace :api do
    namespace :v1 do
      resources :issues, only: [] do
        resources :pages, only: [:index, :show], param: :position
      end
    end
  end

  devise_for :users, only: [:omniauth_callbacks], path: '', controllers: { omniauth_callbacks: "auth/omniauth_callbacks" }

  resources :comments

  resources :materials, path: 'm', only: [] do
    get '(:id)' => 'materials#show', as: :show
  end

  resources :issues, path: '', only: [] do
    get 'advertisement' => 'issues#advertisement', as: :advertisement
    get 'interstitial'  => 'issues#interstitial',  as: :interstitial

    get '/preview/(:id)' => 'issues#previewed', as: :previewed
    get '(:id)' => 'issues#published', as: :published

    get '/:article_id/gallery' => 'issue_media#index', as: :gallery
  end
  root 'issues#published'

end

app/models/media.rb
class Media < ApplicationRecord
  belongs_to :article, counter_cache: true
  belongs_to :creator, class_name: 'User'
  belongs_to :issue

  validates :article, :creator, presence: true

  before_create :assign_issue
  before_validation :prepend_http

  mount_uploader :asset, PhotoUploader
  process_in_background :asset

  include FriendlyID

  before_save :assign_position, :assign_media_type

  def presentation_url
    ( self.asset.blank? ) ? self.override_url : self.asset_url
  end

  def thumbnail
    if self.asset.blank?
      url = 'https://s3-us-west-2.amazonaws.com/shiftdrink/static/video-icon.png'
    else
      url = self.asset_url
    end
    
    url
  end

  protected
    def assign_position
      self.position = self.article.media_count + 1 if self.position.nil?
    end

    def assign_media_type
      self.media_type = ( self.asset.blank? ) ? 'Video' : 'Photo'
    end

    def assign_issue
      self.issue_id = self.article.issue_id
    end

    def prepend_http
      self.override_url = "http://#{override_url}" unless self.override_url =~ /^https?:\/\//
    end
end

app/controllers/admin/media_controller.rb
class Admin::MediaController < Admin::BaseController
  before_action :find_issue, :find_article
  before_action :find_media, only: [:edit, :update, :destroy]

  # load_and_authorize_resource :class => Media, :find_by => :friendly_id

  # => GET /issues/:issue_id/:article_id/media
  def index
    @medias = @article.medias.includes(:issue).order(:position)
  end

  # => GET /issues/:issue_id/:article_id/media/new
  def new
  end

  # => POST /issues/:issue_id/:article_id/media
  def create
    @media = @article.medias.new media_params.merge(creator: current_user)

    if @media.save
      redirect_to media_path(@issue, @article), notice: 'Media added successfully'
    else
      flash.now[:danger] = @media.first_error_message
      redirect_to media_path(@issue, @article)
    end
  end

  # => POST /issues/:issue_id/:article_id/media/multiple
  def multiple
    params[:medias][:asset].each do |asset|
      @article.medias.create!(asset: asset, creator: current_user)
    end

    redirect_to media_path(@issue, @article), notice: 'Media added successfully'
  end

  # => GET /issues/:issue_id/:article_id/media/:id/edit
  def edit
  end

  # => PATCH /issues/:issue_id/:article_id/media/:id
  def update
    if @media.update media_params
      redirect_to edit_medium_path(@issue, @article, @media), notice: 'Media updated successfully'
    else
      flash.now[:danger] = @article.first_error_message
      redirect_to edit_medium_path(@issue, @article, @media)
    end
  end

  # => DELETE /issues/:issue_id/:article_id/media/:id
  def destroy
    @media.destroy
    redirect_to media_path(@issue, @article), notice: 'Media has been removed' 
  end

  protected
    def find_media
      @media = Media.find_by! friendly_id: params[:id]
    end

    def media_params
      params.require(:media).permit(:asset, :override_url)
    end
end

app/views/admin/media/_caption.html.erb
<% if can?(:administrate, Media) %>
    <div class="caption">
		<p class="no-margin">
			<%= link_to('Edit', edit_medium_path(@issue, @article, media), :class => 'label label-default') %>

			<%= link_to('Remove', medium_path(@issue, @article, media), method: :delete,
					:class => 'label label-danger', data: { confirm: 'Are you sure you want to remove this page?' }) %>
		</p>
	</div>
<% end %>

app/views/admin/media/edit.html.erb
<% content_for :title do %>
	<%= render 'admin/shared/heads' %>
 	<p>MEDIA EDITOR - EDIT</p>
<% end %>

<% content_for :buttons do %>

<% end %>

<% content_for :page_content do %>
	<div class="col-md-6">
	  <div class="panel panel-default">
	    <div class="panel-heading">Edit Media Object</div>

      	<%= simple_form_for(@media, url: medium_path(@issue, @article, @media), method: :patch) do |f| %>
			<div class="panel-body">
				<div class="form-group">
					<%= f.input :override_url, error: false, input_html: { :class => 'form-control' }, label: 'Override URL' %>
				</div>
				<div class="form-group">
					<%= f.input :asset, error: false, input_html: { :class => 'form-control' }, label: 'Image' %>

					<% if @media.asset.present? %>
						<div class="well" style="word-break: break-all; padding: 10px; border-radius: 0">
							<small><%= link_to @media.asset_url, @media.asset_url, :target => '_blank' %></small>
						</div>
					<% end %>
				</div>
			</div>

			<div class="panel-footer">
				<%= f.button :submit, :class => 'btn btn-primary btn-sm' %>

				<%= link_to('Remove Media', medium_path(@issue, @article, @media),
					:class => 'btn btn-danger btn-sm', method: :delete,
					:data  => { confirm: 'Are you sure you want to remove this article and all its pages?' }) %>
			</div>
      	<% end %>
	  </div>
	</div>
<% end %>

<%= render 'admin/shared/layout' %>

app/views/admin/media/index.html.erb
<% content_for :title do %>
	<%= render 'admin/shared/heads' %>
 	<p>MEDIA GALLERY</p>
<% end %>

<% content_for :buttons do %>
	<% if can?(:administrate, Media) %>
		<%= link_to new_medium_path(@issue, @article), :class => 'btn btn-labeled btn-default' do %>
			<span class="btn-label"><i class="fa fa-plus"></i></span> Create New
		<% end %>

		<a role="button" class="btn btn-labeled btn-default" id="create-media">
			<span class="btn-label"><i class="fa fa-files-o"></i></span> Create Multiple
		</a>

		<%= form_for(:media, url: multiple_media_path(@issue, @article), html: { multipart: true, id: 'new_media', :class => 'hidden' }, method: :post) do |f| %>
		     <%= f.file_field :asset, multiple: true, name: "medias[asset][]", :class => 'hidden', onchange: 'this.form.submit()' %>
		<% end %>
	<% end %>

	<%= link_to pages_path(@issue, @article), :class => 'btn btn-labeled btn-default' do %>
		<span class="btn-label"><i class="fa fa-file-o"></i></span> View Article
	<% end %>

	<%= link_to issue_gallery_url(@issue, @article, subdomain: 'www'), :class => 'btn btn-labeled btn-default', :target => '_blank' do %>
		<span class="btn-label"><i class="fa fa-eye"></i></span> Preview
	<% end %>
<% end %>

<% content_for :page_content do %>
<div id="medias" class="<%= @issue.role.downcase %> sortable" data-href="<%= sort_media_url(@issue, @article) %>">
	<% unless @medias.nil? %>
		<% @medias.each do |media| %>
			<div class="col-md-3" data-identifier="<%= media.id %>">
				<div class="thumbnail">
					<%= render 'admin/media/caption', media: media %>

					<%= thumbnail_for_media(media) %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>
<% end %>

<%= render 'admin/shared/layout' %>

app/views/admin/media/new.html.erb
<% content_for :title do %>
	<%= render 'admin/shared/heads' %>
 	<p>MEDIA EDITOR - NEW</p>
<% end %>

<% content_for :buttons do %>

<% end %>

<% content_for :page_content do %>
	<div class="col-md-6">
	  <div class="panel panel-default">
	    <div class="panel-heading">Edit Media Object</div>

      	<%= simple_form_for(:media, url: media_path(@issue, @article)) do |f| %>
			<div class="panel-body">
				<div class="form-group">
					<%= f.input :override_url, error: false, input_html: { :class => 'form-control' }, label: 'From the web' %>
				</div>

				<div class="form-group">
					<%= f.input :asset, as: :file, error: false, input_html: { :class => 'form-control' }, label: 'From your files' %>
				</div>
			</div>

			<div class="panel-footer">
				<%= f.button :submit, :class => 'btn btn-primary btn-sm' %>
			</div>
      	<% end %>
	  </div>
	</div>

	<div class="col-md-5">

	</div>
<% end %>

<%= render 'admin/shared/layout' %>