config/routes.rb
Rails.application.routes.draw do
	get '/.well-known/acme-challenge/Gcl13AN0SUH1veBZY_05y2Yv-WUWno3N5fG_2oV7h8A' => 'welcome#letsencrypt'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951/' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.html' => 'welcome#loaderio'
	get '/loaderio-89df6155f1caf8969ffbbc4eb70e9951.txt' => 'welcome#loaderio'

  devise_for :users, scope: :admin, path: 'admin', skip: [:registrations, :omniauth_callbacks]

	get '/issue-desktop', to: redirect('/')
	get '/issue-mobile/:id', to: redirect('/m-issue/%{id}')
	get '/issue-desktop/:id', to: redirect('/issue/%{id}')
	get '/issue-archive', to: redirect('/')
	get '/archive-desktop/:id', to: redirect('/archives/%{id}')
	get '/archive-mobile/:id', to: redirect('/m-archives/%{id}')

  scope :admin, :module => 'admin' do
    resources :materials
		resources :author
		resources :comments

    resources :issues do
      resources :articles, except: [:index, :show, :new] do
        collection { patch :sort }
      end
    end

    scope :path => '/issues/:issue_id/:article_id' do
      resources :pages, except: [:show] do
        collection { patch :sort }

        delete 'thumbnail' => 'pages#remove_thumb', as: :remove_thumb

        resources :hyperlinks
      end

      resources :media, except: [:show] do
        collection { patch :sort }
      end

      post 'media/multiple' => 'media#multiple', as: :multiple_media
    end

    resources :analytics

    resources :users

    scope :account do
      get   'settings' => 'account#index',    as: :account_settings
      patch 'password' => 'account#password', as: :account_password
      patch 'profile'  => 'account#profile',  as: :account_profile
    end

    get '/' => 'issues#index'
  end

  namespace :api do
    namespace :v1 do
      resources :issues, only: [] do
        resources :pages, only: [:index, :show], param: :position
      end
    end
  end

  devise_for :users, only: [:omniauth_callbacks], path: '', controllers: { omniauth_callbacks: "auth/omniauth_callbacks" }

  resources :comments

  resources :materials, path: 'm', only: [] do
    get '(:id)' => 'materials#show', as: :show
  end

  resources :issues, path: '', only: [] do
    get 'advertisement' => 'issues#advertisement', as: :advertisement
    get 'interstitial'  => 'issues#interstitial',  as: :interstitial

    get '/preview/(:id)' => 'issues#previewed', as: :previewed
    get '(:id)' => 'issues#published', as: :published

    get '/:article_id/gallery' => 'issue_media#index', as: :gallery
  end
  root 'issues#published'

end

app/models/issue.rb
class Issue < ApplicationRecord
  scope :published, 							-> { where('published_on IS NOT NULL') }
  scope :publications,      			-> { where(role: 'Issue') }
  scope :materials,         			-> { where(role: 'Material') }

  belongs_to :creator, class_name: 'User'

  has_many :articles, dependent: :destroy
  has_many :pages, through: :articles, dependent: :destroy

	validates :title, presence: true
  validates :alias_name, presence: true
  validates :orientation, presence: true, :inclusion => { :in => ['mobile', 'desktop'] }

  validates :number, presence: true, uniqueness: { case_sensitive: false }, :if => lambda { self.role == 'Issue' }
  validates :number, allow_blank: true, format: { with: /\A[0-9][0-9][0-9]\z/ }

  validates :alias_name, presence: true, uniqueness: { case_sensitive: false }, :if => lambda { self.role == 'Issue' }
  validates :alias_name, format: { with: /\A[a-zA-Z0-9-]+\z/ }

  before_validation :assign_friendly_id
  before_create :assign_preview_token
  after_create :save_first_article

  def to_param
		alias_name
  end

  def is_issue?
    role == 'Issue'
  end

  def displayed_title
    ( self.is_issue? ) ? "Issue #{number}: #{title}" : title
  end

  def first_article
    articles.order(:position).first
  end

  def issue_format
		sizes = FastImage.size(self.front_page.image_url)
		"#{sizes[0]} x #{sizes[1]}"
  end

  # SPEC TBD
  def front_page
    first_article.front_page
  end

  protected
    def save_first_article
      articles.create(title: 'Change Article Title')
    end

    def assign_friendly_id
      self.friendly_id = self.title.parameterize
    end

    def assign_preview_token
      self.preview_token = loop do
        random = SecureRandom.urlsafe_base64(8, false)
        break random unless self.class.exists?(preview_token: random)
      end
    end
end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < Admin::BaseController
  before_action :find_issue, only: [:edit, :update, :destroy]

  load_and_authorize_resource

  # => GET /admin/issues
  def index
    @issues = Issue.publications.order(:number)
  end

  # => POST /admin/issues
  def create
    @issue = Issue.new issue_params.merge(creator: current_user)

    if @issue.save
      redirect_to issues_path, notice: 'Issue was successfully created'
    else
      flash.now[:danger] = @issue.first_error_message
      render :new
    end
  end

  # => GET /admin/issues/:id/edit
  def edit
  end

  # => PATCH /admin/issues/:id
  def update
    if @issue.update(issue_params)
      redirect_to edit_issue_path(@issue), notice: 'Issue was successfully updated'
    else
      flash.now[:danger] = @issue.first_error_message
      render :edit
    end
  end
  
  # => DELETE /admin/issues/:id
  def destroy
  end

  protected
    def issue_params
      params.require(:issue).permit(:number, :alias_name, :title, :orientation, :published_on)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  skip_before_action :authenticate_user!

  before_action :check_device, :only => :published

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  layout 'client'

  # GET => /issues/:id
  def published
    @issue = Issue.published.find_by!(alias_name: params[:issue_id])
    find_resources()
  end

  def previewed
    @issue = Issue.find_by!(preview_token: params[:issue_id])

    find_resources()
  end

  def advertisement
    respond_to do |format|
      format.js { render 'issues/ads' }
    end
  end

  def interstitial
    respond_to do |format|
      format.js { render 'issues/interstitial' }
    end
  end

  protected
    def find_resources()
      @page = @issue.pages.find_by(friendly_id: params[:id]) unless params[:id].blank?
      @thumbnails = @issue.pages.where("pages.position = 1 OR coalesce(advertisement_thumb, '') != ''")
      @articles = @issue.articles.order(:position)
      @current_article = @articles.select{|a| a.id == @page.try(:article_id) }[0]
      @current_article = @articles.first if @current_article.blank?
      @front_page = @current_article.front_page
    end

    def check_device
			(params[:test]) ? return : (0);
			if (!params[:issue_id])
				redirect_to ((browser.device.mobile? || browser.device.tablet? ) ? "/m-issue" : "/issue")
			elsif ((browser.device.mobile? || browser.device.tablet?) && !params[:issue_id].include?("m-"))
        complete_path = "m-"
				params[:issue_id] = complete_path + params[:issue_id]
	      redirect_to "/#{params[:issue_id]}/#{params[:id]}"
			elsif (!(browser.device.mobile? || browser.device.tablet?) && params[:issue_id].include?("m-"))
				params[:issue_id] = params[:issue_id][2,params[:issue_id].length]
				redirect_to "/#{params[:issue_id]}/#{params[:id]}"
      end
		end
end

app/helpers/admin/issues_helper.rb
module Admin::IssuesHelper
  def thumbnail_for(issue)
    front_page = issue.front_page
    
    if front_page.nil?
      image_tag 'https://s3-us-west-2.amazonaws.com/shiftdrink/static/default/issue-cover.jpg'
    else
      image_tag front_page.image_url(:large)
    end
  end

  def issue_numbers
    (1..50).map {|n| ["%03d" % n, "%03d" % n] }
  end

  def issue_count
    "%03d" % ( Issue.publications.count + 1 )
  end
end

app/views/issues/shared/_advertisements.html.erb
<% if !browser.device.mobile? && !browser.device.tablet? %>
	<div class="ad ad-sky ad-skyscraper">
		<small class="advertise-with-us"><a href="/<%= @issue.alias_name %>/advertise-with-us" target="_blank">Advertise with us</a></small>

		<script type="text/javascript">
		var AdButler = AdButler || {}; AdButler.ads = AdButler.ads || [];
		var abkw = window.abkw || '';

		var plc226343 = window.plc226343 || 0;
		document.write('<'+'div id="placement_226343_'+plc226343+'" class="ad-butler"></'+'div>');
		AdButler.ads.push({handler: function(opt){ AdButler.register(167867, 226343, [160,600], 'placement_226343_'+opt.place, opt); }, opt: { place: plc226343++, keywords: abkw, domain: 'ab167867.adbutler-ikon.com', click:'CLICK_MACRO_PLACEHOLDER' }});
		</script>
	</div>
	<div class="ad ad-sky ad-skyscraper2">
		<small class="advertise-with-us"><a href="/<%= @issue.alias_name %>/advertise-with-us" target="_blank">Advertise with us</a></small>

		<script type="text/javascript">
		var AdButler = AdButler || {}; AdButler.ads = AdButler.ads || [];
		var abkw = window.abkw || '';

		var plc226343 = window.plc226343 || 0;
		document.write('<'+'div id="placement_226343_'+plc226343+'" class="ad-butler"></'+'div>');
		AdButler.ads.push({handler: function(opt){ AdButler.register(167867, 226343, [160,600], 'placement_226343_'+opt.place, opt); }, opt: { place: plc226343++, keywords: abkw, domain: 'ab167867.adbutler-ikon.com', click:'CLICK_MACRO_PLACEHOLDER' }});
		</script>
	</div>
<% end %>

app/views/issues/shared/_bottom.html.erb
<%= link_to user_omniauth_authorize_path(:facebook), :class => 'subs_free', :target => '_blank' do %>
	SUBSCRIBE</br>FOR FREE
<% end %>
<div id="bottom-bar">
  <div class="navigation">
    <ul class="left-navigation">
      <% if @issue.is_issue? %>
        <li id="toggle-comments">
          <%= link_to comments_path, :remote => true do %>
            <i class="fa fa-comments" aria-hidden="true"></i>
          <% end %>
					<img src="https://d2y1ry8g49t2dy.cloudfront.net/static/arrows-in-vector-format.png"/>
        </li>
      <% end %>

      <li id="toggle-thumbs">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </li>
    </ul>
		<div id="title_pic">
			<img />
		</div>
    <% if @issue.is_issue?  %>
      <%= render 'issues/shared/social_buttons' %>
    <% end %>
  </div><!-- /.navigation -->
</div><!-- #bottom-bar -->

<% unless controller_name === 'materials' %>

	<div class="hidden" id="refresh-ad">
	  <%= link_to '', issue_advertisement_path, remote: true %>
	</div>

	<div class="hidden" id="refresh-interstitial">
	  <%= link_to '', issue_interstitial_path, remote: true %>
	</div>

<% end %>

app/views/issues/shared/_comments_tab.html.erb
<div class="comments-tab">
	<span>see the comments</br> & editor's notes?</span>
	<i class="exit fa fa-times"></i>
</div>

app/views/issues/shared/_content.html.erb
<div id="comments">
	<div id="comments-spinner">
	  <i class="fa fa-spinner fa-3x fa-pulse"></i>
	</div>

	<%= render partial: "comments/template", locals: {commentable: @article } %>
</div>

<% unless controller_name === 'materials' %>
	<%= render('issues/shared/interstitial') %>
<% end %>

<% unless box_position(@page.try(:master_position), -1) < 1 %>
  <div id="box<%= box_position @page.try(:master_position), -1 %>" class="box left">
	<img src="" alt="" usemap="">

	<div class="map"></div>
  </div>
<% end %>

<div id="box<%= box_position @page.try(:master_position) %>" class="box center">
	<img src="" alt="" usemap="">

	<div class="map"></div>
</div>

<div id="box<%= box_position @page.try(:master_position), 1 %>" class="box">
	<img src="" alt="" usemap="">

	<div class="map"></div>
</div>

<div id="box<%= box_position @page.try(:master_position), 2 %>" class="box">
	<img src="" alt="">

	<div class="map"></div>
</div>

<div class="arrow prev">
	<div class="arrow-offset"></div>
</div>
<div class="arrow next">
	<div class="arrow-offset"></div>
</div>
<img class="swipe" src="https://d2y1ry8g49t2dy.cloudfront.net/static/swipe.svg">
</img>

<input type="hidden" id="position" value="<%= @page.try(:master_position) || 1 %>">
<input type="hidden" id="issue_id" value="<%= @issue.id %>">

<input type="hidden" id="article_id" value="">

app/views/issues/shared/_corner.html.erb
<div class="followers">
	<div class="close-followers-prompt">
		<i class="fa fa-times"></i>
	</div>
	<div class="stage1">
		<h4>More than a shitty website.</h4>
		<h3>Or we like to think so.</h3>
		<%= link_to user_omniauth_authorize_path(:facebook), :class => 'btn btn-block btn-social-login facebook', :target => '_blank' do %>
			<span class="fa fa-facebook-square"></span><span class="subscribe_text"> Subscribe with Facebook</span>
		<% end %>
	</div>
	<div class="stage2">
		<h4>We are a free magazine.</h4>
		<h3>An IG follow is the least you can do.</h3>
		<a href="https://www.instagram.com/realtheshiftdrink/?ref=badge" target="_blank" class="ig-b- ig-b-v-24">
			<img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" />
		</a>
		<script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/cd688a73093057ec8e166f80414e3cff.html" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 95%; border: 0; overflow: hidden;"></iframe>
	</div>
	<% if !current_user %>
		<div class="stage3">
			<h4>For the Industry. By the Industry.</h4>
			<h3>Join the community.</h3>
			<div class="fb-page"
				data-href="https://www.facebook.com/realtheshiftdrink"
				data-width="300"
				data-hide-cover="true"
				data-show-facepile="true"
				data-small-header="true"></div>
		</div>
	<% end %>
</div>

app/views/issues/shared/_interstitial.html.erb
<div class="interstitial-container">
	<div class="ad-butler"></div>

	<div class="close-interstitial">
		<a role="button">[Close]</a>
	</div>
</div>

<div class="interstitial"></div>

app/views/issues/shared/_popup.html.erb
<div id="bio_ep_close"><span class="fa fa-times"></span></div>
<div id="bio_ep">
	<div class="bio_ep_content">
		<div class="bio_ep_head">
			<img src="http://d2y1ry8g49t2dy.cloudfront.net/static/shift_drink.png">
		</div>
		<div class="bio_ep_body">
			<div class="left">
				<h3>Like what you saw?</h3>
				<p>Please show support for independent media by connecting on <a href="https://www.facebook.com/realtheshiftdrink/" target="_blank">Facebook</a> or any other apps you use in the bathroom while at work</p>
			</div>
			<div class="right">
				<div class="addthis_inline_follow_toolbox"></div>
			</div>
		</div>
		<div class="bio_ep_footer">
			<img src="https://d2y1ry8g49t2dy.cloudfront.net/static/for_the_industry_by_the_industry.png">
		</div>
	</div>
</div>

app/views/issues/shared/_social_buttons.html.erb
<% if @issue.is_issue? %>
	<div class="btn-social">
		<a href="" target="_blank" class="btn btn-twitter" data-social="twitter"
	    onclick="window.open(this.href, 'mywin', 'left=20,top=20,width=500,height=400,toolbar=1,resizable=0'); return false;">
			<span class="btn-text">Tweet</span>
	    <i class="fa fa-twitter"></i>
	  </a>
		
	  <a class="btn btn-facebook" data-social="facebook">
			<span>Share</span>
	    <i class="fa fa-facebook-square"></i>
	  </a>
	</div>
<% end %>